# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis-stack:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  ui:
    build: .
    ports:
      - 3000:3000
volumes:
  db:
  redis:
